OMDjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^OpinionMonitor/', include('OpinionMonitor.urls')),
]

OpinionMonitor/urls.py
from django.conf.urls import url
import OMDjango.settings as settings
from django.views.static import serve

from . import views

app_name = 'OpinionMonitor'
urlpatterns = [
    # 首页
    url(r'^$', views.index, name='index'),
    # 热点图
    url(r'^hot/$', views.hot, name='hot'),
    # 相似文本
    url(r'^sim_txt/', views.sim_txt, name='sim'),
    url(r'^sim_txt_result/', views.sim_txt_result, name='sim_result'),
    # 搜索页面
    url(r'^search/$', views.search, name='search'),
    url(r'^search/kwl/', views.get_keyword_list, name='kwl'),
    url(r'^search/fpl/', views.get_focus_passge_list, name='fpl')
]

OpinionMonitor/models.py
from django.db import models


# Create your models here.
# 热点词汇
class kwl(models.Model):
    kid = models.AutoField(primary_key=True)
    word = models.CharField(max_length=10)
    num = models.PositiveIntegerField(default=0)

    def to_json(self):
        d = dict()
        d[getattr(self, 'word')] = getattr(self, 'num')
        import json
        return json.dumps(d, ensure_ascii=False)

    def to_tuple(self):
        return (getattr(self, 'word'),getattr(self, 'num'))


# 热点文章
class fpl(models.Model):
    pid = models.AutoField('pid', primary_key=True)
    url = models.CharField('url', max_length=100)
    title = models.CharField('title', max_length=50)
    content = models.TextField('content')
    forbiddenNum = models.PositiveSmallIntegerField('fn')
    pTime = models.TimeField('pTime')
    pDate = models.DateField('pDate')
    st = models.FloatField('st', null=True)
    simHash = models.BigIntegerField('simHash', null=True)
    c_read = models.PositiveIntegerField('c_read', default=0)
    c_reply = models.PositiveIntegerField('c_reply', default=0)

    def to_tuple(self):
        return (str(getattr(self, 'pid')) , (getattr(self, 'title'),getattr(self, 'pDate').strftime('%Y-%m-%d'),getattr(self, 'c_read'),getattr(self, 'url')))


class EntityCategory(models.Model):
    ecid = models.SmallIntegerField(primary_key=True)
    word = models.CharField(max_length=5)


class Entity(models.Model):
    eid = models.AutoField(primary_key=True)
    word = models.CharField(max_length=25)
    ec = models.ForeignKey(EntityCategory, on_delete=models.SET_NULL, null=True)


class Keyword(models.Model):
    kid = models.AutoField(primary_key=True)
    word = models.CharField(max_length=10)


class ForbiddenWord(models.Model):
    fid = models.AutoField(primary_key=True)
    word = models.CharField(max_length=10)


class Category(models.Model):
    cid = models.SmallIntegerField(primary_key=True)
    word = models.CharField(max_length=4)


class Passage(models.Model):
    pid = models.AutoField('pid', primary_key=True)
    url = models.CharField('url', max_length=100)
    title = models.CharField('title', max_length=50)
    content = models.TextField('content')
    forbiddenNum = models.PositiveSmallIntegerField('fn')
    pTime = models.TimeField('pTime')
    pDate = models.DateField('pDate')
    st = models.FloatField('st', null=True)
    c_read = models.PositiveIntegerField('c_read', default=0)
    c_reply = models.PositiveIntegerField('c_reply', default=0)
    keywords = models.ManyToManyField(Keyword, through='PassageKeyword')
    entities = models.ManyToManyField(Entity)
    fwords = models.ManyToManyField(ForbiddenWord)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)

    def get_abstract(self, word=None):
        index = 50
        # 有关键词传入
        if word:
            word_list = [word]
            index_list = []
            if " " in word:
                word_list = word.split(" ")
            # 计算偏移
            shift = 50 // len(word_list)
            for key in word_list:
                index = self.content.find(key)
                start_index = 0
                end_index = 0
                mod_index = 0
                if index - shift > 0:
                    start_index = index - shift
                else:
                    mod_index = shift

                if index + shift + mod_index < len(self.content):
                    end_index = index + shift + mod_index
                elif index + shift + mod_index < len(self.content):
                    end_index = index + shift
                else:
                    mod_index = shift
                    if start_index - mod_index > 0:
                        start_index -= mod_index
                    else:
                        start_index = 0
                index_list.append([start_index, end_index])

            result = ""
            for item in index_list:
                result += "..." + self.content[item[0]:item[1]] + "..."

            for key in word_list:
                result = result.replace(key, "<em>"+key+"</em>")
            return result
        else:
            if len(self.content) < 50:
                end_index = len(self.content)
            else:
                end_index = 50
            return "..."+self.content[0:end_index]+"..."

    def to_tuple(self):
        ratio = int(getattr(self, 'st')*100)
        abstract = self.get_abstract()
        return (str(getattr(self, 'pid')) , (getattr(self, 'title'),getattr(self, 'pDate').strftime('%Y-%m-%d'),getattr(self, 'c_read'),getattr(self, 'c_reply'),getattr(self, 'url'), ratio, abstract))

class PassageKeyword(models.Model):
    id = models.AutoField('id', primary_key=True)
    pid = models.ForeignKey(Passage)
    kid = models.ForeignKey(Keyword)
    ratio = models.FloatField('ratio')

OpinionMonitor/views.py
from json import JSONEncoder

from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from OpinionMonitor.models import Passage
from django.shortcuts import render
from .tool import *
from .models import kwl
from .models import fpl
import json
from collections import OrderedDict

# Create your views here.
class IndexView(generic.DetailView):
    template_name = 'OM/index.html'


def index(request):
    return render(request, 'OM/index.html')

def sim_txt(request):
    return render(request, 'OM/sim_txt.html')

def hot(request):
    return render(request,'OM/echart.html')

def search(request):
    page = 0
    if request.method == 'GET':
        if "keyword" in request.GET:
            keyword = request.GET["keyword"]
            print(keyword)
            if "page" in request.GET:
                page = int(request.GET["page"])
            else:
                page = 1
            context = get_search_result(keyword, page)
    return render(request, 'OM/list.html', context)


def sim_txt_result(request):
    r_dict = dict()
    if request.method == 'POST':
        if "s_text" in request.POST:
            r_dict = get_similar_text(request.POST['s_text'])
    return HttpResponse(json.dumps(r_dict, ensure_ascii=False))


def get_keyword_list(request):
    num = 10
    if 'num' in request.GET:
        num = int(request.GET['num'])
    key_word_list = kwl.objects.order_by("-num")[0:num]
    r_list = []
    for keyword in key_word_list:
        w_tuple = keyword.to_tuple()
        r_list.append(w_tuple)
    r_dict = OrderedDict(r_list)
    return HttpResponse(json.dumps(r_dict, ensure_ascii=False))


def get_focus_passge_list(request):
    passage_list = fpl.objects.order_by("-c_read")[0:10]
    r_list = []
    for passage in passage_list:
        p_tuple = passage.to_tuple()
        r_list.append(p_tuple)
    r_dict = OrderedDict(r_list)
    return HttpResponse(json.dumps(r_dict, ensure_ascii=False))

OpinionMonitor/templates/OM/base.html
<!doctype html>
{% load static %}
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>
        {% block title %}
            list
        {% endblock title %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static "OM/css/bootstrap.min.css"%}">
    <link rel="stylesheet" type="text/css" href="{% static "OM/css/nprogress.css"%}">
    <link rel="stylesheet" type="text/css" href="{% static "OM/css/style.css"%}">
    <link rel="stylesheet" type="text/css" href="{% static "OM/css/font-awesome.min.css"%}">
    <link rel="apple-touch-icon-precomposed" href="{% static "OM/images/icon.png" %}">
    <link rel="shortcut icon" href="{% static "OM/images/favicon.png" %}">

    {#自定义的CSS#}
    {% block css %}
    {% endblock %}

</head>


<body class="user-select">
<!-- 导航头开始 -->
<header class="header">
    <nav class="navbar navbar-default" id="navbar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#header-navbar" aria-expanded="false">
                            <span class="sr-only">
                            </span>
                    <span class="icon-bar">
                            </span>
                    <span class="icon-bar">
                            </span>
                    <span class="icon-bar">
                            </span>
                </button>
                <h1 class="logo hvr-bounce-in">
                    <a href="{% url "OpinionMonitor:index" %}" title="舆情分析系统">
                        <img src="{% static "OM/images/201610171329086541.png" %}" alt="舆情分析系统">
                    </a>
                </h1>
            </div>
            <div class="collapse navbar-collapse" id="header-navbar">
                <form class="navbar-form navbar-left" action="{% url 'OpinionMonitor:search' %}" method="get">
                    <div class="input-group"  style="margin-top: 5px; padding-bottom: 2px">
                        <input type="text" name="keyword" class="form-control" value="{{ keyword }}"
                               maxlength="20" autocomplete="off" style="width:400px; margin-left: 100px;">
                        <span class="input-group-btn" style="height: 100%">
                                    <button class="btn btn-default btn-search" type="submit" style="height: auto">
                                        搜索
                                    </button>
                                </span>
                    </div>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a data-cont="首页" title="首页" href="{% url "OpinionMonitor:index" %}">
                            首页
                        </a>
                    </li>
                    <li>
                        <a data-cont="查询" title="查询" href="{% url "OpinionMonitor:search" %}?keyword=杭州">
                            查询
                        </a>
                    </li>
                    <li>
                        <a data-cont="热点" title="热点" href="{% url "OpinionMonitor:hot" %}">
                            热点
                        </a>
                    </li>
                    <li>
                        <a data-cont="预警" title="预警" href="{% url "OpinionMonitor:search" %}?keyword=%敏感文章%">
                            预警
                        </a>
                    </li>
                    <li>
                        <a data-cont="全文匹配" title="全文匹配" href="{% url "OpinionMonitor:sim" %}">
                            全文匹配
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- 导航头结束 -->

{# body #}
{% block body %}
{% endblock %}

{#footer#}
<footer class="footer">
    <div class="container">
        <p>
            Copyright &copy; 2016. Hongli.Chen All rights reserved.
        </p>
    </div>
</footer>

{# 用于模板引擎的动态加载 #}
{% block template %}
{% endblock %}



{#    基础的JavaScript    #}
<script src="{% static "OM/js/jquery-2.1.4.min.js"%}"></script>
<script src="{% static "OM/js/jquery.lazyload.min.js"%}"></script>
<script src="{% static "OM/js/bootstrap.min.js"%}"></script>
<script src="{% static "OM/js/nprogress.js"%}"></script>
<script src="{% static "OM/js/scripts.js"%}"></script>
<!--[if gte IE 9]>
        <script src="{% static "OM/js/jquery-1.11.1.min.js"%}" type="text/javascript">
        </script>
        <script src="{% static "OM/js/html5shiv.min.js"%}" type="text/javascript">
        </script>
        <script src="{% static "OM/js/respond.min.js"%}" type="text/javascript">
        </script>
        <script src="{% static "OM/js/selectivizr-min.js"%}" type="text/javascript">
        </script>
    <![endif]-->
<!--[if lt IE 9]>
        <script>
            window.location.href = 'upgrade-browser.html';
        </script>
    <![endif]-->

{# 自定义的JavaScript #}
{% block js %}
{% endblock %}

</body>


</html>

OpinionMonitor/templates/OM/echart.html
{% extends "OM/base.html" %}
{% load static %}
{% block title %}
    热点
{% endblock %}
{% load static %}
{% block css %}
    <!-- 自定义表格CSS -->
    <link rel="stylesheet" type="text/css" href={% static "OM/css/table.css" %}>
{% endblock %}

{% block body %}
    <div style="background: white">
    <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
    <div class="container">
        <div class="row" >
            <div class="col-md-12" >
                    <div id="main" style="width: 100%;height:500px; "></div>
                    <div id = "div1"></div>
            </div>
        </div>
    </div>

    <div class="container" >
    <!-- 横线 -->
        <div class="row" >
            <div class="col-md-12" >
                        <hr style="height:4px;border:none;border-top:3px solid #E5E5E5;" />

            </div>
        </div>

        <div class="row" id="table_row">
            <div class="col-md-4" style="padding-right: 50px">
                    <table>
                        <thead>
                            <tr>
                                <th>关键词
                                <th>热度
                        </thead>
                        <tbody id="data_table1">
                        </tbody>
                    </table>
            </div>

            <div class="col-md-4" style="padding-right: 50px">
                    <table>
                        <thead>
                            <tr>
                                <th>关键词
                                <th>热度
                        </thead>
                        <tbody id="data_table2">
                        </tbody>
                    </table>
            </div>

            <div class="col-md-4">
                    <table>
                        <thead>
                            <tr>
                                <th>关键词
                                <th>热度
                        </thead>
                        <tbody id="data_table3">
                        </tbody>
                    </table>
            </div>


        </div>

        <div class="row" >
            <div class="col-md-12" >
                <div style="height: 50px"></div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

{% block js %}
    <!-- 引入 ECharts 文件 -->
    <script src={% static "OM/js/echarts.js" %}></script>
    <!-- 执行图标代码 -->
    <script src={% static "OM/js/myechart.js" %}></script>
    <script src={% static "OM/js/g_table.js" %}></script>
{% endblock %}

OpinionMonitor/templates/OM/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

<!-- Page title -->
<title>Home</title>

<!-- Meta -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- Style -->
<link rel="stylesheet" href={% static "OM/css/theme.css" %}>


</head>
<body>

<!-- Preloader -->
<div id="preloader">
<div class="loader"></div>
</div>
<!-- /Preloader -->

<!-- Header -->
<header id="home" class="header">

<!-- Navigation -->
<nav id="navigation" class="navbar affix">

	<div class="container">

		<div class="row">
			<div class="col-md-12">

				<!-- Navigation Header -->
				<div class="navbar-header">

					<!-- Toggle Button -->
					<button type="button"
							class="navbar-toggle collapsed"
							data-toggle="collapse"
							data-target="#main-menu"
							aria-expanded="false"
							aria-controls="main-menu">

						<span class="sr-only">Toggle Navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>

					</button>
					<!-- /Toggle Button -->

					<!-- Brand -->
					<a href="{% url "OpinionMonitor:index" %}" class="brand">

						<!-- Logo Big -->
						<img src= {% static "OM/images/logo.png" %} class="logo-big" alt="">
						<!-- /Logo Big -->

						<!-- Logo Small -->
						<img src= {% static "OM/images/logo-small.png" %} class="logo-small" alt="">
						<!-- /Logo Small -->

					</a>
					<!-- /Brand -->

				</div>
				<!-- /Navigation Header -->

				<!-- Navigation -->
				<div id="main-menu" class="navbar-collapse collapse">
					<ul class="nav navbar-nav navbar-right">
						<li><a href="">Home</a></li>
						<li><a href="javascript:window.scrollTo(1500,1500)">About</a></li>
						<li><a href="javascript:window.scrollTo(1500,1500)">Contact</a></li>
					</ul>
				</div>
				<!-- /Navigation -->

			</div>
		</div>

	</div>
</nav>
<!-- /Navigation -->

</header>
<!-- /Header -->

<!-- Slider -->
<div class="slider owl-carousel owl-theme">

	<!-- Slide -->
	<div class="item mask" style="background: url({% static "OM/images/home.jpg"%}) no-repeat center top / cover;" data-stellar-background-ratio="0.4">

		<div class="container height-100p">
			<div class="row height-100p">

				<div class="col-sm-6 col-md-6 height-100p bounceInLeft wow" data-wow-duration="1.3s" data-wow-delay="0.3s" data-stellar-ratio="0.7">
					<div class="vertical-middle">
						<h1 class="text-white">欢迎使用 <span class="text-theme">舆情分析系统</span></h1>
						<div class="text-white h4">
							舆情分析是针对一定的社会空间内，围绕中介性社会实践的发生、发展和变化。将民众对社会管理者产生和持有的社会政治态度在网络上表达出来的 意愿集合，并进行一定的分析。
						</div>
					</div>
				</div>

				<div class="col-sm-6 col-md-4 col-md-offset-2 height-100p bounceInRight wow" data-wow-duration="1.3s" data-stellar-ratio="0.8">
					<div class="vertical-middle">
						<img src= {% static "OM/images/devices.png" %} class="img-responsive" alt="">
					</div>
				</div>

			</div>
		</div>

	</div>
	<!-- /Slide -->

	<!-- Slide -->
	<div class="item mask" style="background: url({% static "OM/images/home-02.jpg"%}) no-repeat center top / cover;" data-stellar-background-ratio="0.4">

		<div class="container height-100p">
			<div class="row height-100p">

				<div class="col-sm-6 col-md-6 height-100p bounceInLeft wow" data-wow-duration="1.3s" data-wow-delay="0.3s" data-stellar-ratio="0.7">
					<div class="vertical-middle">
						<h1 class="text-white">系统 <span class="text-theme">主要功能</span></h1>
						<div class="text-white h4">
							基于杭州19楼论坛数据，提取论坛讨论的热点，对每篇文章进行相应的分析计算。
						</div>
					</div>
				</div>

				<div class="col-sm-6 col-md-4 col-md-offset-2 height-100p bounceInRight wow" data-wow-duration="1.3s" data-stellar-ratio="0.8">
					<div class="vertical-middle">
						<img src="{% static "OM/images/devices.png" %}" class="img-responsive" alt="">
					</div>
				</div>

			</div>
		</div>

	</div>
	<!-- /Slide -->

</div>
<!-- /Slider -->

<!-- Main -->
<main class="main-container">

<!-- Section: About -->
<section id="about" class="section">
	<div class="container">

		<!-- Section Header -->
		<div class="row" style="display: none">
			<div class="col-md-6 col-md-offset-3">
				<header class="text-center">
					<h2 class="section-title">About <span class="text-theme">Us</span></h2>
					<p class="section-subtitle">It is a long established fact that a reader</p>
				</header>
			</div>
		</div>
		<!-- /Section Header -->

		<div class="row">

			<!-- Feature Block -->
			<a href="search/?keyword=杭州" class="btn_url">
			<div class="col-sm-3 feature fadeIn wow" data-wow-duration="1.3s">
				<span class="glyphicon glyphicon-search icon"></span>
				<div class="h3 title">舆情查询</div>
				<p class="description">
					对特定关键词的舆情进行搜索，准确而丰富的搜索结果让你快速了解并掌握关心话题的最新动态。
				</p>
			</div>
			</a>
			<!-- /Feature Block -->

			<!-- Feature Block -->
            <a href="hot/" class="btn_url">
                <div class="col-sm-3 feature fadeIn wow" data-wow-duration="1.3s" data-wow-delay="0.4s">
                    <span class="glyphicon glyphicon-fire icon"></span>
                    <div class="h3 title">舆情热点</div>
                    <p class="description">
                        通过特定的排序算法，提取论坛数据中最受关注的话题，让你快速掌握当然舆论热点的所在。
                    </p>
                </div>
            </a>
			<!-- /Feature Block -->

			<!-- Feature Block -->
            <a href="search/?keyword=%敏感文章%" class="btn_url">
                <div class="col-sm-3 feature fadeIn wow" data-wow-duration="1.3s" data-wow-delay="0.8s">
                    <span class="glyphicon glyphicon-screenshot icon"></span>
                    <div class="h3 title">舆情预警</div>
                    <p class="description">
                        通过情感分析，敏感词识别，及早发现危机的苗头，对可能产生的现实危机的走向、规模进行判断。
                    </p>
                </div>
            </a>
			<!-- /Feature Block -->
			
			<!-- Feature Block -->
            <a href="sim_txt" class="btn_url">
                <div class="col-sm-3 feature fadeIn wow" data-wow-duration="1.3s" data-wow-delay="0.8s">
                    <span class="glyphicon glyphicon-flash icon"></span>
                    <div class="h3 title">全文匹配</div>
                    <p class="description">
                        输入待检索的文章，利用相关文字处理算法，自动分析文章的主要内容，匹配类似文章进行展示。
                    </p>
                    <!-- <a href="#" class="btn btn-theme">开始</a> -->
                </div>
            </a>
			<!-- /Feature Block -->

		</div>
	</div>
</section>


</main>
<!-- /Main -->

<!-- Footer -->
<footer class="footer section-small">
<div class="container">
	<div class="row">

		<!-- Footer Column -->
		<div class="col-md-2 col-xs-6 footer-col">

		    <span class="point-icon">
		        <span class="glyphicon glyphicon-user" aria-hidden="true">
		        </span>
		    </span>
		    <span>
		        Name: 陈泓历
		    </span>

		</div>
		<!-- /Footer Column -->

		<!-- Footer Column -->
		<div class="col-md-3 col-xs-6 footer-col">
		    <span class="point-icon">
		        <span class="glyphicon glyphicon-map-marker" aria-hidden="true">
		        </span>
		    </span>
		    <span>
		        杭州电子科技大学通信工程学院
		    </span>
		</div>
		<!-- /Footer Column -->

		<!-- Footer Column -->
		<div class="col-md-3 col-xs-6 footer-col">
		    <span class="point-icon">
		        <span class="glyphicon glyphicon-envelope" aria-hidden="true">
		        </span>
		    </span>
		    <span>
		        <a href="mailto:hongliryan@gmail.com" style="color:white">
		            hongliryan@gmail.com
		        </a>
		    </span>

		</div>
		<!-- /Footer Column -->

		<!-- Footer Column -->
		<div class="col-md-3 col-xs-6 footer-col">

		    <span class="point-icon" id="phone_number">
		        <span class="glyphicon glyphicon-earphone" aria-hidden="true">
		        </span>
		    </span>
		    <span>
		        Tel: +8615988417835
		    </span>

		</div>
		<!-- /Footer Column -->


	</div>
</div>
</footer>
<!-- /Footer -->

<!-- Scroll To Top -->
<div id="scroll-to-top" class="scroll-to-top">
<i class="icon fa fa-angle-up"></i>
</div>
<!-- /Scroll To Top -->

<!-- Modal: Result Message -->
<div class="modal fade" id="result" role="dialog">
<div class="modal-dialog">
	<div class="modal-content">

		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
				<i class="fa fa-times"></i>
			</button>
			<h4 class="modal-title">Sending message</h4>
		</div>

		<div class="modal-body">

			<div class="result-icon">
				<div class="icon-border">
					<svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" preserveAspectRatio="none">
						<circle cx="8" cy="8" r="6.215" transform="rotate(90 8 8)"></circle>
					</svg>
					<i class="icon fa fa-check"></i>
				</div>
			</div>

			<p class="modal-result h4 text-center"></p>
		</div>

	</div>
</div>
</div>
<!-- /Modal: Result Message -->

<!-- SCRIPTS -->
<script src={% static "OM/js/jquery-2.2.0.min.js" %}></script>
<script src={% static "OM/js/bootstrap.min.js" %}></script>
<script src={% static "OM/js/owl.carousel.min.js" %}></script>
<script src={% static "OM/js/jquery.magnific-popup.min.js" %}></script>
<script src={% static "OM/js/jquery.validate.min.js" %}></script>
<script src={% static "OM/js/jquery.stellar.min.js" %}></script>
<script src={% static "OM/js/wow.min.js" %}></script>
<script src={% static "OM/js/masonry.pkgd.min.js" %}></script>
<script src={% static "OM/js/jquery.appear.js" %}></script>
<script src={% static "OM/js/jquery.animateNumber.min.js" %}></script>
<script src={% static "OM/js/general.js" %}></script>
<!-- /SCRIPTS -->



</body>
</html>

OpinionMonitor/templates/OM/sim_txt.html
{% extends "om/base.html" %}
{% load static %}
{% block title %}
    相似文本
{% endblock %}

{% block css %}
       <link rel="stylesheet" type="text/css" href="{% static "OM/css/sim_txt.css"%}">
{% endblock %}

{% block body %}
<div style="background: #ffffff; padding-top:10px;">
    <div class="container">
    <div class="row">
        <div class="col-md-12">
        <p>
            查找相似文本:
        </p>

            <textarea class="s_text" name="s_text" rows="20" onblur="if(this.value == ''){this.style.color = '#aca899'; this.value = '请输入匹配文字'; }" onfocus="if(this.value == '请输入匹配文字'){this.value =''; this.style.color = '#000000'; } "style="color:#aca899; width: 100%;">请输入匹配文字</textarea>

    <span id="csrf_token">{% csrf_token %}</span>
</div>
    </div>
        <div class="row" style="padding: 10px 0 10px 0">
            <div class="col-md-9"></div>
            <div class="col-md-3 pull-right">
                <div class="pull-right">
                    <input id='txt_button' class='button confirm' type="submit" value="提交" />
                    <input id='clear_button' class='button clear' type="submit" value="清空" />
                </div>
            </div>
        </div>

        <hr>

        <div class="result_text_area">

        </div>


        </div>
</div>

</div>

    {% block template %}
        {% verbatim %}
        <script type="text/html" id="result_passage">



                            <!-- 正文标签开始 -->
                            <div class="col-md-4">
 <article class="excerpt excerpt-1">

     <div class="row">
         <div class="col-md-2">
             <div class="sim_circle">
                 {{ratio}}
             </div>
         </div>
         <div class="col-md-10">
                                <header>
                            <h2>
                                <a href="{{url}}" title="{{title}}" target="_blank">
                                    {{title}}
                                </a>
                            </h2>
                        </header>
                        <p class="meta">
                            <time class="time">
                                <i class="glyphicon glyphicon-time">
                                </i>
                                {{pDate}}
                            </time>
                            <span class="views">
                                <i class="glyphicon glyphicon-eye-open">
                                </i>
                                {{c_read}}
                            </span>
                            <a class="comment" href="#" title="评论" target="_blank">
                                <i class="glyphicon glyphicon-comment">
                                </i>
                                    {{c_reply}}
                            </a>
                        </p>
             </div>
     </div>
                        <p class="note">
                                {{content}}
                        </p>
     </article>
                            </div>
                            <!-- 正文标签结束 -->


</script>
        {% endverbatim %}

    {% endblock %}

{% endblock %}

{% block js %}
    <script src="{% static "OM/js/template.js"%}"></script>
        <script src={% static "om/js/sim_txt.js" %}></script>
{% endblock %}